name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Contribution Graph
        uses: platane/snk@v2
        with:
          github_user_name: your-github-username # Replace this with your GitHub username

      - name: Move Snake Contribution Graph to assets folder
        run: |
          mkdir -p assets
          mv snake.svg assets/snake.svg

      - name: Commit and push Snake Contribution Graph
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/snake.svg'
          message: 'Update Snake contribution graph'

    
  


    
     

      

     
       
          

     
